name Build APK
on push
jobs
  build
    runs-on ubuntu-latest
    steps
      - uses actionscheckout@v3
      - uses actionssetup-java@v3
        with {java-version '17', distribution 'temurin'}
      - run chmod +x gradlew && .gradlew assembleDebug
      - uses actionsupload-artifact@v3
        with
          name PhoneBoard-debug.apk
          path appbuildoutputsapkdebugapp-debug.apk